apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: wo0l6e75m-java-springboot
  janus-idp.io/tekton: wo0l6e75m-java-springboot
  backstage.io/kubernetes-id: wo0l6e75m-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: wo0l6e75m-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
